name: Trigger auto deployment for containerappmfgc5b2lpqq7

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerappmfgc5b2lpqq7-AutoDeployTrigger-5997770a-7432-4bef-b4ff-8750dd9df7b6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: zuhacr.azurecr.io
          username: ${{ secrets.CONTAINERAPPMFGC5B2LPQQ7_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPMFGC5B2LPQQ7_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zuhacr.azurecr.io/containerappmfgc5b2lpqq7:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPMFGC5B2LPQQ7_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerappmfgc5b2lpqq7 -g clitest.rgeootgkzcrkpkz2ki6le2jpytxq4elmgwdu5fhscnoxvpsvbv763raokwg3v7dnwmm --server zuhacr.azurecr.io --username  ${{ secrets.CONTAINERAPPMFGC5B2LPQQ7_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPMFGC5B2LPQQ7_REGISTRY_PASSWORD }}
            az containerapp update -n containerappmfgc5b2lpqq7 -g clitest.rgeootgkzcrkpkz2ki6le2jpytxq4elmgwdu5fhscnoxvpsvbv763raokwg3v7dnwmm --image zuhacr.azurecr.io/containerappmfgc5b2lpqq7:${{ github.sha }}
